# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    # Evita error si no hay token configurado; salta el job silenciosamente
    if: ${{ secrets.FLY_API_TOKEN != '' }}
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c rag_chain/fly.toml -a rag-chain
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
